name: lofaz
version: 1.0.4+5
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: 6.1.0
  nb_utils: ^6.1.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  icons_plus: ^5.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_easyloading: ^3.0.5
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.8.0
  firebase_performance: ^0.9.3+8
  firebase_in_app_messaging: ^0.7.4+8
  in_app_review: ^2.0.9
  flutter_cache_manager: ^3.3.1
  facebook_app_events: ^0.19.1
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  app_bar_with_search_switch: ^1.8.5
  in_app_update: ^4.2.2
  multi_select_flutter: ^4.1.3
  dartz: ^0.10.1
  skeletonizer: ^1.0.1
  textfield_tags: ^3.0.1
  quill_html_editor: ^2.2.7
  smooth_page_indicator: ^1.1.0
  # truecaller_sdk: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

flutter_gen:
  output: lib/app/utils/gen/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lofaz1.png"
